name: Create Zip Archive

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip excluding install.sh
        run: |
          mkdir artifact
          zip -r artifact/copytothebox.zip . -x "install.sh" ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: copytothebox-archive
          path: artifact/copytothebox.zip
